### ISSUE TITLE
PhD collection thesis - \input{} instead of \include{} to include papers

### ISSUE THREAD

**Issue by simonbogh** [jkjaer/aauLatexTemplates#12] opened 2020-12-01 10:14 UTC
For the aauPhdCollectionThesis template I receive an error on `\includepaper{}` when `\include{}` is used in `macros.tex`. 

    I can't write on file `papers/paperA/paperA.aux'.

In `macros.tex`changing `\include{}` to `\input{}` fixes the error 
https://github.com/jkjaer/aauLatexTemplates/blob/bd8638e5ae3e010d8721fca0dcf6c3dbeacdfefe/aauPhdCollectionThesis/setup/macros.tex#L66

Explanation why to use `\input{}` instead of `\include{}`
https://tex.stackexchange.com/questions/2209/how-can-i-include-the-file-somedir-file-tex-in-the-file-somedir-subdir-another/2214#2214

**Comment by jkjaer** [comment] 2020-12-02 18:18
Thanks for taking the time to report issues :)

I have tried to reproduce the bug (on Ubuntu 20.04.1 with TeX Live 2019), but have been unable to do so. The template compiles just fine with the \include{} command. If I change the \include{} command to \input{}, on the other hand, I cannot compile the bibliography anymore since the chapterbib package [1] produces a bibliography for every included file and does not work with the \input{} command. The chapterbib offers a \begin{cbunit}. . .\end{cbunit} environment and a \cbunit{} command as an alternative to the \include{} command, but the compilation procedure seems cumbersome.

What OS and operating system are you using? Are you sure that the reported issue is not a problem with your system? My impression is that quite a few people have used the template, but I have never heard of the issue before.

As I understand the Stack Exchange post, you refer to, you are not allowed to include files from a parent directory (or higher), but can include files from subfolders without any problems. The latter is also what is done in the template since the master.tex file includes the papers in papers/paperX subfolders.

[1] http://texdoc.net/texmf-dist/doc/latex/cite/chapterbib.pdf

**Comment by simonbogh** [comment] 2020-12-02 21:29
Forgot to mention this is running it on overleaf, not sure about their install setup.

**Comment by jkjaer** [comment] 2022-04-03 06:23
Closing this issue since it seems to be an Overleaf issue.

**Closed as completed by jkjaer** 2022-04-03 06:23 UTC
